using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EggLink.DanhengServer.Enums
{
    public enum MissionFinishTypeEnum
    {
        FinishMission = 1,
        Talk = 2,
        StageWin = 3,
        EnterFloor = 4,
        SubMissionFinishCnt = 5,
        PropState = 6,
        GetTrialAvatar = 7,
        DelTrialAvatar = 8,
        KillMonster = 9,
        CreateCharacter = 10,
        MessagePerformSectionFinish = 11,
        ConsumeMissionItem = 12,
        EnterMapByEntrance = 13,
        EnterRaidScene = 14,
        MessageSectionFinish = 15,
        RaidFinishCnt = 16,
        UseSelectedItem = 17,
        LeaveFloor = 18,
        PlayerLevel = 19,
        ItemNum = 20,
        GetItem = 21,
        BoxingClubAccomplish = 22,
        LeavePlane = 23,
        WaitDays = 24,
        BuyShopGoods = 25,
        KillMonsterList = 26,
        NotInFloor = 27,
        TeamLeaderChange = 28,
        GetTrialAvatarList = 29,
        KillMonsterGroupList = 30,
        InteractPropList = 31,
        ChallengeFinishCnt = 32,
        ChallengeFinish = 33,
        CocoonFinish = 34,
        AnyCocoonFinish = 35,
        AnyFarmElementFinish = 36,
        TrainVisitorMissionFinish = 37,
        RoguePassAreaProgress = 38,
        RogueEnterRoomWithLevel = 39,
        PropDestruct = 40,
        RogueExploreScore = 41,
        RogueAreaProgressScore = 42,
        NotInPlane = 43,
        TreasureChestOpenCnt = 44,
        EnterPlane = 45,
        ActivityFightFirstFinishDifficulty = 46,
        PunkLordStageFinish = 47,
        KillMonsterInBattle = 48,
        MuseumWorkDayCnt = 49,
        MuseumPhaseFinish = 50,
        ActivityExpeditionFinishCnt = 51,
        AlleyNormalOrderFinish = 52,
        AlleyLogisticsShopLink = 53,
        AlleySpecialOrderFinishById = 54,
        TreasureDungeonAccomplish = 55,
        RogueDLCEnterLayerCnt = 56,
        RogueDLCFinishCnt = 57,
        RogueDLCFinishWithMainStoryCnt = 58,
        RogueDLCFinishWithSubStoryGroupCnt = 59,
        AetherDivideCertainFinishHyperlinkDuel = 60,
        AetherDivideCollectSpiritType = 61,
        HeliobusSnsSpecialComment = 62,
        HeliobusPhase = 63,
        RogueNousFinishStoryCnt = 64,
        SpaceZooHybridCount = 65,
        SpaceZooUnlockSpecialID = 66,
        SpaceZooExpPoint = 67,
        SpaceZooOpCatteryCount = 68,
        ActivityStrongChallengeEndScore = 69,
        ActivityStrongChallengeBegin = 70,
        ChallengeStorySettleCnt = 71,
    }
}
