// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChessRogueStartScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ChessRogueStartScRsp.proto</summary>
  public static partial class ChessRogueStartScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for ChessRogueStartScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChessRogueStartScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpDaGVzc1JvZ3VlU3RhcnRTY1JzcC5wcm90bxobQ2hlc3NSb2d1ZUN1cnJl",
            "bnRJbmZvLnByb3RvGhBMaW5ldXBJbmZvLnByb3RvGhhDaGVzc1JvZ3VlQ2Vs",
            "bEluZm8ucHJvdG8aD1NjZW5lSW5mby5wcm90bxoUQ2hlc3NSb2d1ZUluZm8u",
            "cHJvdG8i4AEKFENoZXNzUm9ndWVTdGFydFNjUnNwEg8KB3JldGNvZGUYAiAB",
            "KA0SLAoMY3VycmVudF9pbmZvGAogASgLMhYuQ2hlc3NSb2d1ZUN1cnJlbnRJ",
            "bmZvEhsKBmxpbmV1cBgBIAEoCzILLkxpbmV1cEluZm8SJgoJY2VsbF9pbmZv",
            "GAcgASgLMhMuQ2hlc3NSb2d1ZUNlbGxJbmZvEhkKBXNjZW5lGAQgASgLMgou",
            "U2NlbmVJbmZvEikKEGNoZXNzX3JvZ3VlX2luZm8YCyABKAsyDy5DaGVzc1Jv",
            "Z3VlSW5mb0IeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.ChessRogueCurrentInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.LineupInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.ChessRogueCellInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.SceneInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.ChessRogueInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.ChessRogueStartScRsp), global::EggLink.DanhengServer.Proto.ChessRogueStartScRsp.Parser, new[]{ "Retcode", "CurrentInfo", "Lineup", "CellInfo", "Scene", "ChessRogueInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChessRogueStartScRsp : pb::IMessage<ChessRogueStartScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChessRogueStartScRsp> _parser = new pb::MessageParser<ChessRogueStartScRsp>(() => new ChessRogueStartScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChessRogueStartScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.ChessRogueStartScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueStartScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueStartScRsp(ChessRogueStartScRsp other) : this() {
      retcode_ = other.retcode_;
      currentInfo_ = other.currentInfo_ != null ? other.currentInfo_.Clone() : null;
      lineup_ = other.lineup_ != null ? other.lineup_.Clone() : null;
      cellInfo_ = other.cellInfo_ != null ? other.cellInfo_.Clone() : null;
      scene_ = other.scene_ != null ? other.scene_.Clone() : null;
      chessRogueInfo_ = other.chessRogueInfo_ != null ? other.chessRogueInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueStartScRsp Clone() {
      return new ChessRogueStartScRsp(this);
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 2;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "current_info" field.</summary>
    public const int CurrentInfoFieldNumber = 10;
    private global::EggLink.DanhengServer.Proto.ChessRogueCurrentInfo currentInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueCurrentInfo CurrentInfo {
      get { return currentInfo_; }
      set {
        currentInfo_ = value;
      }
    }

    /// <summary>Field number for the "lineup" field.</summary>
    public const int LineupFieldNumber = 1;
    private global::EggLink.DanhengServer.Proto.LineupInfo lineup_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.LineupInfo Lineup {
      get { return lineup_; }
      set {
        lineup_ = value;
      }
    }

    /// <summary>Field number for the "cell_info" field.</summary>
    public const int CellInfoFieldNumber = 7;
    private global::EggLink.DanhengServer.Proto.ChessRogueCellInfo cellInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueCellInfo CellInfo {
      get { return cellInfo_; }
      set {
        cellInfo_ = value;
      }
    }

    /// <summary>Field number for the "scene" field.</summary>
    public const int SceneFieldNumber = 4;
    private global::EggLink.DanhengServer.Proto.SceneInfo scene_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.SceneInfo Scene {
      get { return scene_; }
      set {
        scene_ = value;
      }
    }

    /// <summary>Field number for the "chess_rogue_info" field.</summary>
    public const int ChessRogueInfoFieldNumber = 11;
    private global::EggLink.DanhengServer.Proto.ChessRogueInfo chessRogueInfo_;
    /// <summary>
    ///HLODEEONDBF OBGFEMEOJCE = 13;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueInfo ChessRogueInfo {
      get { return chessRogueInfo_; }
      set {
        chessRogueInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChessRogueStartScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChessRogueStartScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Retcode != other.Retcode) return false;
      if (!object.Equals(CurrentInfo, other.CurrentInfo)) return false;
      if (!object.Equals(Lineup, other.Lineup)) return false;
      if (!object.Equals(CellInfo, other.CellInfo)) return false;
      if (!object.Equals(Scene, other.Scene)) return false;
      if (!object.Equals(ChessRogueInfo, other.ChessRogueInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (currentInfo_ != null) hash ^= CurrentInfo.GetHashCode();
      if (lineup_ != null) hash ^= Lineup.GetHashCode();
      if (cellInfo_ != null) hash ^= CellInfo.GetHashCode();
      if (scene_ != null) hash ^= Scene.GetHashCode();
      if (chessRogueInfo_ != null) hash ^= ChessRogueInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (lineup_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Lineup);
      }
      if (Retcode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Retcode);
      }
      if (scene_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Scene);
      }
      if (cellInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CellInfo);
      }
      if (currentInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(CurrentInfo);
      }
      if (chessRogueInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(ChessRogueInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (lineup_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Lineup);
      }
      if (Retcode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Retcode);
      }
      if (scene_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Scene);
      }
      if (cellInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CellInfo);
      }
      if (currentInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(CurrentInfo);
      }
      if (chessRogueInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(ChessRogueInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (currentInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentInfo);
      }
      if (lineup_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Lineup);
      }
      if (cellInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CellInfo);
      }
      if (scene_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Scene);
      }
      if (chessRogueInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChessRogueInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChessRogueStartScRsp other) {
      if (other == null) {
        return;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.currentInfo_ != null) {
        if (currentInfo_ == null) {
          CurrentInfo = new global::EggLink.DanhengServer.Proto.ChessRogueCurrentInfo();
        }
        CurrentInfo.MergeFrom(other.CurrentInfo);
      }
      if (other.lineup_ != null) {
        if (lineup_ == null) {
          Lineup = new global::EggLink.DanhengServer.Proto.LineupInfo();
        }
        Lineup.MergeFrom(other.Lineup);
      }
      if (other.cellInfo_ != null) {
        if (cellInfo_ == null) {
          CellInfo = new global::EggLink.DanhengServer.Proto.ChessRogueCellInfo();
        }
        CellInfo.MergeFrom(other.CellInfo);
      }
      if (other.scene_ != null) {
        if (scene_ == null) {
          Scene = new global::EggLink.DanhengServer.Proto.SceneInfo();
        }
        Scene.MergeFrom(other.Scene);
      }
      if (other.chessRogueInfo_ != null) {
        if (chessRogueInfo_ == null) {
          ChessRogueInfo = new global::EggLink.DanhengServer.Proto.ChessRogueInfo();
        }
        ChessRogueInfo.MergeFrom(other.ChessRogueInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (lineup_ == null) {
              Lineup = new global::EggLink.DanhengServer.Proto.LineupInfo();
            }
            input.ReadMessage(Lineup);
            break;
          }
          case 16: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 34: {
            if (scene_ == null) {
              Scene = new global::EggLink.DanhengServer.Proto.SceneInfo();
            }
            input.ReadMessage(Scene);
            break;
          }
          case 58: {
            if (cellInfo_ == null) {
              CellInfo = new global::EggLink.DanhengServer.Proto.ChessRogueCellInfo();
            }
            input.ReadMessage(CellInfo);
            break;
          }
          case 82: {
            if (currentInfo_ == null) {
              CurrentInfo = new global::EggLink.DanhengServer.Proto.ChessRogueCurrentInfo();
            }
            input.ReadMessage(CurrentInfo);
            break;
          }
          case 90: {
            if (chessRogueInfo_ == null) {
              ChessRogueInfo = new global::EggLink.DanhengServer.Proto.ChessRogueInfo();
            }
            input.ReadMessage(ChessRogueInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (lineup_ == null) {
              Lineup = new global::EggLink.DanhengServer.Proto.LineupInfo();
            }
            input.ReadMessage(Lineup);
            break;
          }
          case 16: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 34: {
            if (scene_ == null) {
              Scene = new global::EggLink.DanhengServer.Proto.SceneInfo();
            }
            input.ReadMessage(Scene);
            break;
          }
          case 58: {
            if (cellInfo_ == null) {
              CellInfo = new global::EggLink.DanhengServer.Proto.ChessRogueCellInfo();
            }
            input.ReadMessage(CellInfo);
            break;
          }
          case 82: {
            if (currentInfo_ == null) {
              CurrentInfo = new global::EggLink.DanhengServer.Proto.ChessRogueCurrentInfo();
            }
            input.ReadMessage(CurrentInfo);
            break;
          }
          case 90: {
            if (chessRogueInfo_ == null) {
              ChessRogueInfo = new global::EggLink.DanhengServer.Proto.ChessRogueInfo();
            }
            input.ReadMessage(ChessRogueInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
