// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChessRogueCellUpdateNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ChessRogueCellUpdateNotify.proto</summary>
  public static partial class ChessRogueCellUpdateNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for ChessRogueCellUpdateNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChessRogueCellUpdateNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBDaGVzc1JvZ3VlQ2VsbFVwZGF0ZU5vdGlmeS5wcm90bxokQ2hlc3NSb2d1",
            "ZUNlbGxVcGRhdGVSZWFzb25UeXBlLnByb3RvGh1Sb2d1ZU1vZGlmaWVyU291",
            "cmNlVHlwZS5wcm90bxoUQmVmb3JlQ2VsbERhdGEucHJvdG8itQEKGkNoZXNz",
            "Um9ndWVDZWxsVXBkYXRlTm90aWZ5EhMKC0tERUdLSUFLRUpBGAYgASgNEi0K",
            "C3NvdXJjZV90eXBlGAcgASgOMhguUm9ndWVNb2RpZmllclNvdXJjZVR5cGUS",
            "IgoJY2VsbF9kYXRhGAogAygLMg8uQmVmb3JlQ2VsbERhdGESLwoGcmVhc29u",
            "GAwgASgOMh8uQ2hlc3NSb2d1ZUNlbGxVcGRhdGVSZWFzb25UeXBlQh6qAhtF",
            "Z2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonTypeReflection.Descriptor, global::EggLink.DanhengServer.Proto.RogueModifierSourceTypeReflection.Descriptor, global::EggLink.DanhengServer.Proto.BeforeCellDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateNotify), global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateNotify.Parser, new[]{ "KDEGKIAKEJA", "SourceType", "CellData", "Reason" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChessRogueCellUpdateNotify : pb::IMessage<ChessRogueCellUpdateNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChessRogueCellUpdateNotify> _parser = new pb::MessageParser<ChessRogueCellUpdateNotify>(() => new ChessRogueCellUpdateNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChessRogueCellUpdateNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueCellUpdateNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueCellUpdateNotify(ChessRogueCellUpdateNotify other) : this() {
      kDEGKIAKEJA_ = other.kDEGKIAKEJA_;
      sourceType_ = other.sourceType_;
      cellData_ = other.cellData_.Clone();
      reason_ = other.reason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueCellUpdateNotify Clone() {
      return new ChessRogueCellUpdateNotify(this);
    }

    /// <summary>Field number for the "KDEGKIAKEJA" field.</summary>
    public const int KDEGKIAKEJAFieldNumber = 6;
    private uint kDEGKIAKEJA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KDEGKIAKEJA {
      get { return kDEGKIAKEJA_; }
      set {
        kDEGKIAKEJA_ = value;
      }
    }

    /// <summary>Field number for the "source_type" field.</summary>
    public const int SourceTypeFieldNumber = 7;
    private global::EggLink.DanhengServer.Proto.RogueModifierSourceType sourceType_ = global::EggLink.DanhengServer.Proto.RogueModifierSourceType.RogueModifierSourceNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.RogueModifierSourceType SourceType {
      get { return sourceType_; }
      set {
        sourceType_ = value;
      }
    }

    /// <summary>Field number for the "cell_data" field.</summary>
    public const int CellDataFieldNumber = 10;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.BeforeCellData> _repeated_cellData_codec
        = pb::FieldCodec.ForMessage(82, global::EggLink.DanhengServer.Proto.BeforeCellData.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.BeforeCellData> cellData_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.BeforeCellData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.BeforeCellData> CellData {
      get { return cellData_; }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 12;
    private global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType reason_ = global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType.ChessRogueCellUpdateReasonNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChessRogueCellUpdateNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChessRogueCellUpdateNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KDEGKIAKEJA != other.KDEGKIAKEJA) return false;
      if (SourceType != other.SourceType) return false;
      if(!cellData_.Equals(other.cellData_)) return false;
      if (Reason != other.Reason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (KDEGKIAKEJA != 0) hash ^= KDEGKIAKEJA.GetHashCode();
      if (SourceType != global::EggLink.DanhengServer.Proto.RogueModifierSourceType.RogueModifierSourceNone) hash ^= SourceType.GetHashCode();
      hash ^= cellData_.GetHashCode();
      if (Reason != global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType.ChessRogueCellUpdateReasonNone) hash ^= Reason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KDEGKIAKEJA != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(KDEGKIAKEJA);
      }
      if (SourceType != global::EggLink.DanhengServer.Proto.RogueModifierSourceType.RogueModifierSourceNone) {
        output.WriteRawTag(56);
        output.WriteEnum((int) SourceType);
      }
      cellData_.WriteTo(output, _repeated_cellData_codec);
      if (Reason != global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType.ChessRogueCellUpdateReasonNone) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KDEGKIAKEJA != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(KDEGKIAKEJA);
      }
      if (SourceType != global::EggLink.DanhengServer.Proto.RogueModifierSourceType.RogueModifierSourceNone) {
        output.WriteRawTag(56);
        output.WriteEnum((int) SourceType);
      }
      cellData_.WriteTo(ref output, _repeated_cellData_codec);
      if (Reason != global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType.ChessRogueCellUpdateReasonNone) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (KDEGKIAKEJA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KDEGKIAKEJA);
      }
      if (SourceType != global::EggLink.DanhengServer.Proto.RogueModifierSourceType.RogueModifierSourceNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SourceType);
      }
      size += cellData_.CalculateSize(_repeated_cellData_codec);
      if (Reason != global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType.ChessRogueCellUpdateReasonNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChessRogueCellUpdateNotify other) {
      if (other == null) {
        return;
      }
      if (other.KDEGKIAKEJA != 0) {
        KDEGKIAKEJA = other.KDEGKIAKEJA;
      }
      if (other.SourceType != global::EggLink.DanhengServer.Proto.RogueModifierSourceType.RogueModifierSourceNone) {
        SourceType = other.SourceType;
      }
      cellData_.Add(other.cellData_);
      if (other.Reason != global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType.ChessRogueCellUpdateReasonNone) {
        Reason = other.Reason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 48: {
            KDEGKIAKEJA = input.ReadUInt32();
            break;
          }
          case 56: {
            SourceType = (global::EggLink.DanhengServer.Proto.RogueModifierSourceType) input.ReadEnum();
            break;
          }
          case 82: {
            cellData_.AddEntriesFrom(input, _repeated_cellData_codec);
            break;
          }
          case 96: {
            Reason = (global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 48: {
            KDEGKIAKEJA = input.ReadUInt32();
            break;
          }
          case 56: {
            SourceType = (global::EggLink.DanhengServer.Proto.RogueModifierSourceType) input.ReadEnum();
            break;
          }
          case 82: {
            cellData_.AddEntriesFrom(ref input, _repeated_cellData_codec);
            break;
          }
          case 96: {
            Reason = (global::EggLink.DanhengServer.Proto.ChessRogueCellUpdateReasonType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
