// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CLMDKHDHIOB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from CLMDKHDHIOB.proto</summary>
  public static partial class CLMDKHDHIOBReflection {

    #region Descriptor
    /// <summary>File descriptor for CLMDKHDHIOB.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CLMDKHDHIOBReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDTE1ES0hESElPQi5wcm90byr+BAoLQ0xNREtIREhJT0ISLworUk9HVUVf",
            "Q09NTU9OX0FDVElPTl9SRVNVTFRfU09VUkNFX1RZUEVfTk9ORRAAEjEKLVJP",
            "R1VFX0NPTU1PTl9BQ1RJT05fUkVTVUxUX1NPVVJDRV9UWVBFX1NFTEVDVBAB",
            "EjIKLlJPR1VFX0NPTU1PTl9BQ1RJT05fUkVTVUxUX1NPVVJDRV9UWVBFX0VO",
            "SEFOQ0UQAhIyCi5ST0dVRV9DT01NT05fQUNUSU9OX1JFU1VMVF9TT1VSQ0Vf",
            "VFlQRV9NSVJBQ0xFEAMSMwovUk9HVUVfQ09NTU9OX0FDVElPTl9SRVNVTFRf",
            "U09VUkNFX1RZUEVfRElBTE9HVUUQBBIwCixST0dVRV9DT01NT05fQUNUSU9O",
            "X1JFU1VMVF9TT1VSQ0VfVFlQRV9CT05VUxAFEi8KK1JPR1VFX0NPTU1PTl9B",
            "Q1RJT05fUkVTVUxUX1NPVVJDRV9UWVBFX1NIT1AQBhIvCitST0dVRV9DT01N",
            "T05fQUNUSU9OX1JFU1VMVF9TT1VSQ0VfVFlQRV9ESUNFEAcSLworUk9HVUVf",
            "Q09NTU9OX0FDVElPTl9SRVNVTFRfU09VUkNFX1RZUEVfQUVPThAIEjYKMlJP",
            "R1VFX0NPTU1PTl9BQ1RJT05fUkVTVUxUX1NPVVJDRV9UWVBFX0JPQVJEX0VW",
            "RU5UEAkSNQoxUk9HVUVfQ09NTU9OX0FDVElPTl9SRVNVTFRfU09VUkNFX1RZ",
            "UEVfTUFaRV9TS0lMTBAKEjoKNlJPR1VFX0NPTU1PTl9BQ1RJT05fUkVTVUxU",
            "X1NPVVJDRV9UWVBFX0xFVkVMX01FQ0hBTklTTRALQh6qAhtFZ2dMaW5rLkRh",
            "bmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.CLMDKHDHIOB), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CLMDKHDHIOB {
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_NONE")] RogueCommonActionResultSourceTypeNone = 0,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_SELECT")] RogueCommonActionResultSourceTypeSelect = 1,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_ENHANCE")] RogueCommonActionResultSourceTypeEnhance = 2,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_MIRACLE")] RogueCommonActionResultSourceTypeMiracle = 3,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_DIALOGUE")] RogueCommonActionResultSourceTypeDialogue = 4,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_BONUS")] RogueCommonActionResultSourceTypeBonus = 5,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_SHOP")] RogueCommonActionResultSourceTypeShop = 6,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_DICE")] RogueCommonActionResultSourceTypeDice = 7,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_AEON")] RogueCommonActionResultSourceTypeAeon = 8,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_BOARD_EVENT")] RogueCommonActionResultSourceTypeBoardEvent = 9,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_MAZE_SKILL")] RogueCommonActionResultSourceTypeMazeSkill = 10,
    [pbr::OriginalName("ROGUE_COMMON_ACTION_RESULT_SOURCE_TYPE_LEVEL_MECHANISM")] RogueCommonActionResultSourceTypeLevelMechanism = 11,
  }

  #endregion

}

#endregion Designer generated code
