// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FAAMGANKLPE.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from FAAMGANKLPE.proto</summary>
  public static partial class FAAMGANKLPEReflection {

    #region Descriptor
    /// <summary>File descriptor for FAAMGANKLPE.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FAAMGANKLPEReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFGQUFNR0FOS0xQRS5wcm90bxoVUm9ndWVDb21tb25CdWZmLnByb3RvIkkK",
            "C0ZBQU1HQU5LTFBFEiUKC0RFS0ZFRUZPQkJFGAogAygLMhAuUm9ndWVDb21t",
            "b25CdWZmEhMKC0pERExHRE5PSUVDGAIgASgNQh6qAhtFZ2dMaW5rLkRhbmhl",
            "bmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.RogueCommonBuffReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.FAAMGANKLPE), global::EggLink.DanhengServer.Proto.FAAMGANKLPE.Parser, new[]{ "DEKFEEFOBBE", "JDDLGDNOIEC" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FAAMGANKLPE : pb::IMessage<FAAMGANKLPE>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FAAMGANKLPE> _parser = new pb::MessageParser<FAAMGANKLPE>(() => new FAAMGANKLPE());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FAAMGANKLPE> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.FAAMGANKLPEReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FAAMGANKLPE() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FAAMGANKLPE(FAAMGANKLPE other) : this() {
      dEKFEEFOBBE_ = other.dEKFEEFOBBE_.Clone();
      jDDLGDNOIEC_ = other.jDDLGDNOIEC_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FAAMGANKLPE Clone() {
      return new FAAMGANKLPE(this);
    }

    /// <summary>Field number for the "DEKFEEFOBBE" field.</summary>
    public const int DEKFEEFOBBEFieldNumber = 10;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.RogueCommonBuff> _repeated_dEKFEEFOBBE_codec
        = pb::FieldCodec.ForMessage(82, global::EggLink.DanhengServer.Proto.RogueCommonBuff.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RogueCommonBuff> dEKFEEFOBBE_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RogueCommonBuff>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RogueCommonBuff> DEKFEEFOBBE {
      get { return dEKFEEFOBBE_; }
    }

    /// <summary>Field number for the "JDDLGDNOIEC" field.</summary>
    public const int JDDLGDNOIECFieldNumber = 2;
    private uint jDDLGDNOIEC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JDDLGDNOIEC {
      get { return jDDLGDNOIEC_; }
      set {
        jDDLGDNOIEC_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FAAMGANKLPE);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FAAMGANKLPE other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dEKFEEFOBBE_.Equals(other.dEKFEEFOBBE_)) return false;
      if (JDDLGDNOIEC != other.JDDLGDNOIEC) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dEKFEEFOBBE_.GetHashCode();
      if (JDDLGDNOIEC != 0) hash ^= JDDLGDNOIEC.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (JDDLGDNOIEC != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JDDLGDNOIEC);
      }
      dEKFEEFOBBE_.WriteTo(output, _repeated_dEKFEEFOBBE_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (JDDLGDNOIEC != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(JDDLGDNOIEC);
      }
      dEKFEEFOBBE_.WriteTo(ref output, _repeated_dEKFEEFOBBE_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += dEKFEEFOBBE_.CalculateSize(_repeated_dEKFEEFOBBE_codec);
      if (JDDLGDNOIEC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JDDLGDNOIEC);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FAAMGANKLPE other) {
      if (other == null) {
        return;
      }
      dEKFEEFOBBE_.Add(other.dEKFEEFOBBE_);
      if (other.JDDLGDNOIEC != 0) {
        JDDLGDNOIEC = other.JDDLGDNOIEC;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            JDDLGDNOIEC = input.ReadUInt32();
            break;
          }
          case 82: {
            dEKFEEFOBBE_.AddEntriesFrom(input, _repeated_dEKFEEFOBBE_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            JDDLGDNOIEC = input.ReadUInt32();
            break;
          }
          case 82: {
            dEKFEEFOBBE_.AddEntriesFrom(ref input, _repeated_dEKFEEFOBBE_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
