// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FinishEmotionDialoguePerformanceCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from FinishEmotionDialoguePerformanceCsReq.proto</summary>
  public static partial class FinishEmotionDialoguePerformanceCsReqReflection {

    #region Descriptor
    /// <summary>File descriptor for FinishEmotionDialoguePerformanceCsReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FinishEmotionDialoguePerformanceCsReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitGaW5pc2hFbW90aW9uRGlhbG9ndWVQZXJmb3JtYW5jZUNzUmVxLnByb3Rv",
            "ImYKJUZpbmlzaEVtb3Rpb25EaWFsb2d1ZVBlcmZvcm1hbmNlQ3NSZXESEwoL",
            "TklETkdQT0xITkUYByABKA0SEwoLRUNEQkFOQUlQTUoYCSABKA0SEwoLSExP",
            "Q0tFTEZGRkoYCyABKA1CHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90",
            "b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.FinishEmotionDialoguePerformanceCsReq), global::EggLink.DanhengServer.Proto.FinishEmotionDialoguePerformanceCsReq.Parser, new[]{ "NIDNGPOLHNE", "ECDBANAIPMJ", "HLOCKELFFFJ" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FinishEmotionDialoguePerformanceCsReq : pb::IMessage<FinishEmotionDialoguePerformanceCsReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FinishEmotionDialoguePerformanceCsReq> _parser = new pb::MessageParser<FinishEmotionDialoguePerformanceCsReq>(() => new FinishEmotionDialoguePerformanceCsReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FinishEmotionDialoguePerformanceCsReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.FinishEmotionDialoguePerformanceCsReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishEmotionDialoguePerformanceCsReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishEmotionDialoguePerformanceCsReq(FinishEmotionDialoguePerformanceCsReq other) : this() {
      nIDNGPOLHNE_ = other.nIDNGPOLHNE_;
      eCDBANAIPMJ_ = other.eCDBANAIPMJ_;
      hLOCKELFFFJ_ = other.hLOCKELFFFJ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishEmotionDialoguePerformanceCsReq Clone() {
      return new FinishEmotionDialoguePerformanceCsReq(this);
    }

    /// <summary>Field number for the "NIDNGPOLHNE" field.</summary>
    public const int NIDNGPOLHNEFieldNumber = 7;
    private uint nIDNGPOLHNE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NIDNGPOLHNE {
      get { return nIDNGPOLHNE_; }
      set {
        nIDNGPOLHNE_ = value;
      }
    }

    /// <summary>Field number for the "ECDBANAIPMJ" field.</summary>
    public const int ECDBANAIPMJFieldNumber = 9;
    private uint eCDBANAIPMJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ECDBANAIPMJ {
      get { return eCDBANAIPMJ_; }
      set {
        eCDBANAIPMJ_ = value;
      }
    }

    /// <summary>Field number for the "HLOCKELFFFJ" field.</summary>
    public const int HLOCKELFFFJFieldNumber = 11;
    private uint hLOCKELFFFJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HLOCKELFFFJ {
      get { return hLOCKELFFFJ_; }
      set {
        hLOCKELFFFJ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FinishEmotionDialoguePerformanceCsReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FinishEmotionDialoguePerformanceCsReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NIDNGPOLHNE != other.NIDNGPOLHNE) return false;
      if (ECDBANAIPMJ != other.ECDBANAIPMJ) return false;
      if (HLOCKELFFFJ != other.HLOCKELFFFJ) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NIDNGPOLHNE != 0) hash ^= NIDNGPOLHNE.GetHashCode();
      if (ECDBANAIPMJ != 0) hash ^= ECDBANAIPMJ.GetHashCode();
      if (HLOCKELFFFJ != 0) hash ^= HLOCKELFFFJ.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NIDNGPOLHNE != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(NIDNGPOLHNE);
      }
      if (ECDBANAIPMJ != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(ECDBANAIPMJ);
      }
      if (HLOCKELFFFJ != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(HLOCKELFFFJ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NIDNGPOLHNE != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(NIDNGPOLHNE);
      }
      if (ECDBANAIPMJ != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(ECDBANAIPMJ);
      }
      if (HLOCKELFFFJ != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(HLOCKELFFFJ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NIDNGPOLHNE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NIDNGPOLHNE);
      }
      if (ECDBANAIPMJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ECDBANAIPMJ);
      }
      if (HLOCKELFFFJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HLOCKELFFFJ);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FinishEmotionDialoguePerformanceCsReq other) {
      if (other == null) {
        return;
      }
      if (other.NIDNGPOLHNE != 0) {
        NIDNGPOLHNE = other.NIDNGPOLHNE;
      }
      if (other.ECDBANAIPMJ != 0) {
        ECDBANAIPMJ = other.ECDBANAIPMJ;
      }
      if (other.HLOCKELFFFJ != 0) {
        HLOCKELFFFJ = other.HLOCKELFFFJ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 56: {
            NIDNGPOLHNE = input.ReadUInt32();
            break;
          }
          case 72: {
            ECDBANAIPMJ = input.ReadUInt32();
            break;
          }
          case 88: {
            HLOCKELFFFJ = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 56: {
            NIDNGPOLHNE = input.ReadUInt32();
            break;
          }
          case 72: {
            ECDBANAIPMJ = input.ReadUInt32();
            break;
          }
          case 88: {
            HLOCKELFFFJ = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
