// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GFMCNMKHGNP.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GFMCNMKHGNP.proto</summary>
  public static partial class GFMCNMKHGNPReflection {

    #region Descriptor
    /// <summary>File descriptor for GFMCNMKHGNP.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GFMCNMKHGNPReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHRk1DTk1LSEdOUC5wcm90byJhCgtHRk1DTk1LSEdOUBITCgtDTE1FTU1C",
            "TURHShgBIAEoDRITCgtKTERKQkJDQUxCTRgHIAMoDRITCgtHSkpNQk9HUEFJ",
            "TRgKIAEoCBITCgtFT0JCTUdBT01MRRgJIAEoDUIeqgIbRWdnTGluay5EYW5o",
            "ZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GFMCNMKHGNP), global::EggLink.DanhengServer.Proto.GFMCNMKHGNP.Parser, new[]{ "CLMEMMBMDGJ", "JLDJBBCALBM", "GJJMBOGPAIM", "EOBBMGAOMLE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GFMCNMKHGNP : pb::IMessage<GFMCNMKHGNP>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GFMCNMKHGNP> _parser = new pb::MessageParser<GFMCNMKHGNP>(() => new GFMCNMKHGNP());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GFMCNMKHGNP> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GFMCNMKHGNPReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GFMCNMKHGNP() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GFMCNMKHGNP(GFMCNMKHGNP other) : this() {
      cLMEMMBMDGJ_ = other.cLMEMMBMDGJ_;
      jLDJBBCALBM_ = other.jLDJBBCALBM_.Clone();
      gJJMBOGPAIM_ = other.gJJMBOGPAIM_;
      eOBBMGAOMLE_ = other.eOBBMGAOMLE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GFMCNMKHGNP Clone() {
      return new GFMCNMKHGNP(this);
    }

    /// <summary>Field number for the "CLMEMMBMDGJ" field.</summary>
    public const int CLMEMMBMDGJFieldNumber = 1;
    private uint cLMEMMBMDGJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CLMEMMBMDGJ {
      get { return cLMEMMBMDGJ_; }
      set {
        cLMEMMBMDGJ_ = value;
      }
    }

    /// <summary>Field number for the "JLDJBBCALBM" field.</summary>
    public const int JLDJBBCALBMFieldNumber = 7;
    private static readonly pb::FieldCodec<uint> _repeated_jLDJBBCALBM_codec
        = pb::FieldCodec.ForUInt32(58);
    private readonly pbc::RepeatedField<uint> jLDJBBCALBM_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> JLDJBBCALBM {
      get { return jLDJBBCALBM_; }
    }

    /// <summary>Field number for the "GJJMBOGPAIM" field.</summary>
    public const int GJJMBOGPAIMFieldNumber = 10;
    private bool gJJMBOGPAIM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool GJJMBOGPAIM {
      get { return gJJMBOGPAIM_; }
      set {
        gJJMBOGPAIM_ = value;
      }
    }

    /// <summary>Field number for the "EOBBMGAOMLE" field.</summary>
    public const int EOBBMGAOMLEFieldNumber = 9;
    private uint eOBBMGAOMLE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EOBBMGAOMLE {
      get { return eOBBMGAOMLE_; }
      set {
        eOBBMGAOMLE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GFMCNMKHGNP);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GFMCNMKHGNP other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CLMEMMBMDGJ != other.CLMEMMBMDGJ) return false;
      if(!jLDJBBCALBM_.Equals(other.jLDJBBCALBM_)) return false;
      if (GJJMBOGPAIM != other.GJJMBOGPAIM) return false;
      if (EOBBMGAOMLE != other.EOBBMGAOMLE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CLMEMMBMDGJ != 0) hash ^= CLMEMMBMDGJ.GetHashCode();
      hash ^= jLDJBBCALBM_.GetHashCode();
      if (GJJMBOGPAIM != false) hash ^= GJJMBOGPAIM.GetHashCode();
      if (EOBBMGAOMLE != 0) hash ^= EOBBMGAOMLE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CLMEMMBMDGJ != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(CLMEMMBMDGJ);
      }
      jLDJBBCALBM_.WriteTo(output, _repeated_jLDJBBCALBM_codec);
      if (EOBBMGAOMLE != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(EOBBMGAOMLE);
      }
      if (GJJMBOGPAIM != false) {
        output.WriteRawTag(80);
        output.WriteBool(GJJMBOGPAIM);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CLMEMMBMDGJ != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(CLMEMMBMDGJ);
      }
      jLDJBBCALBM_.WriteTo(ref output, _repeated_jLDJBBCALBM_codec);
      if (EOBBMGAOMLE != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(EOBBMGAOMLE);
      }
      if (GJJMBOGPAIM != false) {
        output.WriteRawTag(80);
        output.WriteBool(GJJMBOGPAIM);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CLMEMMBMDGJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CLMEMMBMDGJ);
      }
      size += jLDJBBCALBM_.CalculateSize(_repeated_jLDJBBCALBM_codec);
      if (GJJMBOGPAIM != false) {
        size += 1 + 1;
      }
      if (EOBBMGAOMLE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EOBBMGAOMLE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GFMCNMKHGNP other) {
      if (other == null) {
        return;
      }
      if (other.CLMEMMBMDGJ != 0) {
        CLMEMMBMDGJ = other.CLMEMMBMDGJ;
      }
      jLDJBBCALBM_.Add(other.jLDJBBCALBM_);
      if (other.GJJMBOGPAIM != false) {
        GJJMBOGPAIM = other.GJJMBOGPAIM;
      }
      if (other.EOBBMGAOMLE != 0) {
        EOBBMGAOMLE = other.EOBBMGAOMLE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CLMEMMBMDGJ = input.ReadUInt32();
            break;
          }
          case 58:
          case 56: {
            jLDJBBCALBM_.AddEntriesFrom(input, _repeated_jLDJBBCALBM_codec);
            break;
          }
          case 72: {
            EOBBMGAOMLE = input.ReadUInt32();
            break;
          }
          case 80: {
            GJJMBOGPAIM = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CLMEMMBMDGJ = input.ReadUInt32();
            break;
          }
          case 58:
          case 56: {
            jLDJBBCALBM_.AddEntriesFrom(ref input, _repeated_jLDJBBCALBM_codec);
            break;
          }
          case 72: {
            EOBBMGAOMLE = input.ReadUInt32();
            break;
          }
          case 80: {
            GJJMBOGPAIM = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
