// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: JOCEFLLMNDO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from JOCEFLLMNDO.proto</summary>
  public static partial class JOCEFLLMNDOReflection {

    #region Descriptor
    /// <summary>File descriptor for JOCEFLLMNDO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JOCEFLLMNDOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFKT0NFRkxMTU5ETy5wcm90bxoRRE9KSUZCT0dKRUwucHJvdG8ibwoLSk9D",
            "RUZMTE1ORE8SEwoLSlBHRk9JRU5JRkEYCSABKA0SEwoLSVBGTUJQTFBBQUQY",
            "ASABKA0SEwoLQURCQ0NFTUpISUkYCiABKA0SIQoLTkNJQVBJTU1PSU4YAyAD",
            "KAsyDC5ET0pJRkJPR0pFTEIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlBy",
            "b3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.DOJIFBOGJELReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.JOCEFLLMNDO), global::EggLink.DanhengServer.Proto.JOCEFLLMNDO.Parser, new[]{ "JPGFOIENIFA", "IPFMBPLPAAD", "ADBCCEMJHII", "NCIAPIMMOIN" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class JOCEFLLMNDO : pb::IMessage<JOCEFLLMNDO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JOCEFLLMNDO> _parser = new pb::MessageParser<JOCEFLLMNDO>(() => new JOCEFLLMNDO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<JOCEFLLMNDO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.JOCEFLLMNDOReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JOCEFLLMNDO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JOCEFLLMNDO(JOCEFLLMNDO other) : this() {
      jPGFOIENIFA_ = other.jPGFOIENIFA_;
      iPFMBPLPAAD_ = other.iPFMBPLPAAD_;
      aDBCCEMJHII_ = other.aDBCCEMJHII_;
      nCIAPIMMOIN_ = other.nCIAPIMMOIN_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JOCEFLLMNDO Clone() {
      return new JOCEFLLMNDO(this);
    }

    /// <summary>Field number for the "JPGFOIENIFA" field.</summary>
    public const int JPGFOIENIFAFieldNumber = 9;
    private uint jPGFOIENIFA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JPGFOIENIFA {
      get { return jPGFOIENIFA_; }
      set {
        jPGFOIENIFA_ = value;
      }
    }

    /// <summary>Field number for the "IPFMBPLPAAD" field.</summary>
    public const int IPFMBPLPAADFieldNumber = 1;
    private uint iPFMBPLPAAD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IPFMBPLPAAD {
      get { return iPFMBPLPAAD_; }
      set {
        iPFMBPLPAAD_ = value;
      }
    }

    /// <summary>Field number for the "ADBCCEMJHII" field.</summary>
    public const int ADBCCEMJHIIFieldNumber = 10;
    private uint aDBCCEMJHII_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ADBCCEMJHII {
      get { return aDBCCEMJHII_; }
      set {
        aDBCCEMJHII_ = value;
      }
    }

    /// <summary>Field number for the "NCIAPIMMOIN" field.</summary>
    public const int NCIAPIMMOINFieldNumber = 3;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.DOJIFBOGJEL> _repeated_nCIAPIMMOIN_codec
        = pb::FieldCodec.ForMessage(26, global::EggLink.DanhengServer.Proto.DOJIFBOGJEL.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.DOJIFBOGJEL> nCIAPIMMOIN_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.DOJIFBOGJEL>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.DOJIFBOGJEL> NCIAPIMMOIN {
      get { return nCIAPIMMOIN_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as JOCEFLLMNDO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(JOCEFLLMNDO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (JPGFOIENIFA != other.JPGFOIENIFA) return false;
      if (IPFMBPLPAAD != other.IPFMBPLPAAD) return false;
      if (ADBCCEMJHII != other.ADBCCEMJHII) return false;
      if(!nCIAPIMMOIN_.Equals(other.nCIAPIMMOIN_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (JPGFOIENIFA != 0) hash ^= JPGFOIENIFA.GetHashCode();
      if (IPFMBPLPAAD != 0) hash ^= IPFMBPLPAAD.GetHashCode();
      if (ADBCCEMJHII != 0) hash ^= ADBCCEMJHII.GetHashCode();
      hash ^= nCIAPIMMOIN_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IPFMBPLPAAD != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(IPFMBPLPAAD);
      }
      nCIAPIMMOIN_.WriteTo(output, _repeated_nCIAPIMMOIN_codec);
      if (JPGFOIENIFA != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(JPGFOIENIFA);
      }
      if (ADBCCEMJHII != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(ADBCCEMJHII);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IPFMBPLPAAD != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(IPFMBPLPAAD);
      }
      nCIAPIMMOIN_.WriteTo(ref output, _repeated_nCIAPIMMOIN_codec);
      if (JPGFOIENIFA != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(JPGFOIENIFA);
      }
      if (ADBCCEMJHII != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(ADBCCEMJHII);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (JPGFOIENIFA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JPGFOIENIFA);
      }
      if (IPFMBPLPAAD != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IPFMBPLPAAD);
      }
      if (ADBCCEMJHII != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ADBCCEMJHII);
      }
      size += nCIAPIMMOIN_.CalculateSize(_repeated_nCIAPIMMOIN_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(JOCEFLLMNDO other) {
      if (other == null) {
        return;
      }
      if (other.JPGFOIENIFA != 0) {
        JPGFOIENIFA = other.JPGFOIENIFA;
      }
      if (other.IPFMBPLPAAD != 0) {
        IPFMBPLPAAD = other.IPFMBPLPAAD;
      }
      if (other.ADBCCEMJHII != 0) {
        ADBCCEMJHII = other.ADBCCEMJHII;
      }
      nCIAPIMMOIN_.Add(other.nCIAPIMMOIN_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IPFMBPLPAAD = input.ReadUInt32();
            break;
          }
          case 26: {
            nCIAPIMMOIN_.AddEntriesFrom(input, _repeated_nCIAPIMMOIN_codec);
            break;
          }
          case 72: {
            JPGFOIENIFA = input.ReadUInt32();
            break;
          }
          case 80: {
            ADBCCEMJHII = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IPFMBPLPAAD = input.ReadUInt32();
            break;
          }
          case 26: {
            nCIAPIMMOIN_.AddEntriesFrom(ref input, _repeated_nCIAPIMMOIN_codec);
            break;
          }
          case 72: {
            JPGFOIENIFA = input.ReadUInt32();
            break;
          }
          case 80: {
            ADBCCEMJHII = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
