// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MonopolyGetDailyInitItemScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from MonopolyGetDailyInitItemScRsp.proto</summary>
  public static partial class MonopolyGetDailyInitItemScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for MonopolyGetDailyInitItemScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MonopolyGetDailyInitItemScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNNb25vcG9seUdldERhaWx5SW5pdEl0ZW1TY1JzcC5wcm90byK3AQodTW9u",
            "b3BvbHlHZXREYWlseUluaXRJdGVtU2NSc3ASEgoKcmVzZXRfdGltZRgCIAEo",
            "AxITCgtQT1BFQUxFSEZIQRgKIAEoDRIbChNyZW1vdGVfY29udHJvbF9kaWNl",
            "GA0gASgNEhUKDWluaXRpYWxfbW9uZXkYDiABKA0SDwoHcmV0Y29kZRgBIAEo",
            "DRITCgtub3JtYWxfZGljZRgLIAEoDRITCgtQS0lKR0tFSE5HSxgDIAEoDUIe",
            "qgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.MonopolyGetDailyInitItemScRsp), global::EggLink.DanhengServer.Proto.MonopolyGetDailyInitItemScRsp.Parser, new[]{ "ResetTime", "POPEALEHFHA", "RemoteControlDice", "InitialMoney", "Retcode", "NormalDice", "PKIJGKEHNGK" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MonopolyGetDailyInitItemScRsp : pb::IMessage<MonopolyGetDailyInitItemScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonopolyGetDailyInitItemScRsp> _parser = new pb::MessageParser<MonopolyGetDailyInitItemScRsp>(() => new MonopolyGetDailyInitItemScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonopolyGetDailyInitItemScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.MonopolyGetDailyInitItemScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonopolyGetDailyInitItemScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonopolyGetDailyInitItemScRsp(MonopolyGetDailyInitItemScRsp other) : this() {
      resetTime_ = other.resetTime_;
      pOPEALEHFHA_ = other.pOPEALEHFHA_;
      remoteControlDice_ = other.remoteControlDice_;
      initialMoney_ = other.initialMoney_;
      retcode_ = other.retcode_;
      normalDice_ = other.normalDice_;
      pKIJGKEHNGK_ = other.pKIJGKEHNGK_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonopolyGetDailyInitItemScRsp Clone() {
      return new MonopolyGetDailyInitItemScRsp(this);
    }

    /// <summary>Field number for the "reset_time" field.</summary>
    public const int ResetTimeFieldNumber = 2;
    private long resetTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResetTime {
      get { return resetTime_; }
      set {
        resetTime_ = value;
      }
    }

    /// <summary>Field number for the "POPEALEHFHA" field.</summary>
    public const int POPEALEHFHAFieldNumber = 10;
    private uint pOPEALEHFHA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint POPEALEHFHA {
      get { return pOPEALEHFHA_; }
      set {
        pOPEALEHFHA_ = value;
      }
    }

    /// <summary>Field number for the "remote_control_dice" field.</summary>
    public const int RemoteControlDiceFieldNumber = 13;
    private uint remoteControlDice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RemoteControlDice {
      get { return remoteControlDice_; }
      set {
        remoteControlDice_ = value;
      }
    }

    /// <summary>Field number for the "initial_money" field.</summary>
    public const int InitialMoneyFieldNumber = 14;
    private uint initialMoney_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint InitialMoney {
      get { return initialMoney_; }
      set {
        initialMoney_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 1;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "normal_dice" field.</summary>
    public const int NormalDiceFieldNumber = 11;
    private uint normalDice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NormalDice {
      get { return normalDice_; }
      set {
        normalDice_ = value;
      }
    }

    /// <summary>Field number for the "PKIJGKEHNGK" field.</summary>
    public const int PKIJGKEHNGKFieldNumber = 3;
    private uint pKIJGKEHNGK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PKIJGKEHNGK {
      get { return pKIJGKEHNGK_; }
      set {
        pKIJGKEHNGK_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonopolyGetDailyInitItemScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonopolyGetDailyInitItemScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResetTime != other.ResetTime) return false;
      if (POPEALEHFHA != other.POPEALEHFHA) return false;
      if (RemoteControlDice != other.RemoteControlDice) return false;
      if (InitialMoney != other.InitialMoney) return false;
      if (Retcode != other.Retcode) return false;
      if (NormalDice != other.NormalDice) return false;
      if (PKIJGKEHNGK != other.PKIJGKEHNGK) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResetTime != 0L) hash ^= ResetTime.GetHashCode();
      if (POPEALEHFHA != 0) hash ^= POPEALEHFHA.GetHashCode();
      if (RemoteControlDice != 0) hash ^= RemoteControlDice.GetHashCode();
      if (InitialMoney != 0) hash ^= InitialMoney.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (NormalDice != 0) hash ^= NormalDice.GetHashCode();
      if (PKIJGKEHNGK != 0) hash ^= PKIJGKEHNGK.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Retcode != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Retcode);
      }
      if (ResetTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ResetTime);
      }
      if (PKIJGKEHNGK != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PKIJGKEHNGK);
      }
      if (POPEALEHFHA != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(POPEALEHFHA);
      }
      if (NormalDice != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(NormalDice);
      }
      if (RemoteControlDice != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(RemoteControlDice);
      }
      if (InitialMoney != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(InitialMoney);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Retcode != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Retcode);
      }
      if (ResetTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ResetTime);
      }
      if (PKIJGKEHNGK != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PKIJGKEHNGK);
      }
      if (POPEALEHFHA != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(POPEALEHFHA);
      }
      if (NormalDice != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(NormalDice);
      }
      if (RemoteControlDice != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(RemoteControlDice);
      }
      if (InitialMoney != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(InitialMoney);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResetTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResetTime);
      }
      if (POPEALEHFHA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(POPEALEHFHA);
      }
      if (RemoteControlDice != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RemoteControlDice);
      }
      if (InitialMoney != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InitialMoney);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (NormalDice != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NormalDice);
      }
      if (PKIJGKEHNGK != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PKIJGKEHNGK);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonopolyGetDailyInitItemScRsp other) {
      if (other == null) {
        return;
      }
      if (other.ResetTime != 0L) {
        ResetTime = other.ResetTime;
      }
      if (other.POPEALEHFHA != 0) {
        POPEALEHFHA = other.POPEALEHFHA;
      }
      if (other.RemoteControlDice != 0) {
        RemoteControlDice = other.RemoteControlDice;
      }
      if (other.InitialMoney != 0) {
        InitialMoney = other.InitialMoney;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.NormalDice != 0) {
        NormalDice = other.NormalDice;
      }
      if (other.PKIJGKEHNGK != 0) {
        PKIJGKEHNGK = other.PKIJGKEHNGK;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 16: {
            ResetTime = input.ReadInt64();
            break;
          }
          case 24: {
            PKIJGKEHNGK = input.ReadUInt32();
            break;
          }
          case 80: {
            POPEALEHFHA = input.ReadUInt32();
            break;
          }
          case 88: {
            NormalDice = input.ReadUInt32();
            break;
          }
          case 104: {
            RemoteControlDice = input.ReadUInt32();
            break;
          }
          case 112: {
            InitialMoney = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 16: {
            ResetTime = input.ReadInt64();
            break;
          }
          case 24: {
            PKIJGKEHNGK = input.ReadUInt32();
            break;
          }
          case 80: {
            POPEALEHFHA = input.ReadUInt32();
            break;
          }
          case 88: {
            NormalDice = input.ReadUInt32();
            break;
          }
          case 104: {
            RemoteControlDice = input.ReadUInt32();
            break;
          }
          case 112: {
            InitialMoney = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
