// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OHMOEGIOOFJ.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from OHMOEGIOOFJ.proto</summary>
  public static partial class OHMOEGIOOFJReflection {

    #region Descriptor
    /// <summary>File descriptor for OHMOEGIOOFJ.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OHMOEGIOOFJReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPSE1PRUdJT09GSi5wcm90byK1AQoLT0hNT0VHSU9PRkoSEwoLT0dBRE9E",
            "S0dMTkwYBSABKA0SEwoLQU5HQkZCS0lGREYYCyADKA0SEwoLRkhIRlBPSUFB",
            "QkwYAyADKA0SEwoLQkxFTkxNUERMR0wYByABKAgSEwoLQ1BCTkJKUENOSUUY",
            "DSABKAgSEwoLTk9LSElKQ0lOUEgYCiABKA0SEwoLSENITU9ISEtNRlAYCCAB",
            "KA0SEwoLRkVGRk5DT0VDSEQYAiADKA1CHqoCG0VnZ0xpbmsuRGFuaGVuZ1Nl",
            "cnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.OHMOEGIOOFJ), global::EggLink.DanhengServer.Proto.OHMOEGIOOFJ.Parser, new[]{ "OGADODKGLNL", "ANGBFBKIFDF", "FHHFPOIAABL", "BLENLMPDLGL", "CPBNBJPCNIE", "NOKHIJCINPH", "HCHMOHHKMFP", "FEFFNCOECHD" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OHMOEGIOOFJ : pb::IMessage<OHMOEGIOOFJ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OHMOEGIOOFJ> _parser = new pb::MessageParser<OHMOEGIOOFJ>(() => new OHMOEGIOOFJ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OHMOEGIOOFJ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.OHMOEGIOOFJReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OHMOEGIOOFJ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OHMOEGIOOFJ(OHMOEGIOOFJ other) : this() {
      oGADODKGLNL_ = other.oGADODKGLNL_;
      aNGBFBKIFDF_ = other.aNGBFBKIFDF_.Clone();
      fHHFPOIAABL_ = other.fHHFPOIAABL_.Clone();
      bLENLMPDLGL_ = other.bLENLMPDLGL_;
      cPBNBJPCNIE_ = other.cPBNBJPCNIE_;
      nOKHIJCINPH_ = other.nOKHIJCINPH_;
      hCHMOHHKMFP_ = other.hCHMOHHKMFP_;
      fEFFNCOECHD_ = other.fEFFNCOECHD_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OHMOEGIOOFJ Clone() {
      return new OHMOEGIOOFJ(this);
    }

    /// <summary>Field number for the "OGADODKGLNL" field.</summary>
    public const int OGADODKGLNLFieldNumber = 5;
    private uint oGADODKGLNL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OGADODKGLNL {
      get { return oGADODKGLNL_; }
      set {
        oGADODKGLNL_ = value;
      }
    }

    /// <summary>Field number for the "ANGBFBKIFDF" field.</summary>
    public const int ANGBFBKIFDFFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_aNGBFBKIFDF_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> aNGBFBKIFDF_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> ANGBFBKIFDF {
      get { return aNGBFBKIFDF_; }
    }

    /// <summary>Field number for the "FHHFPOIAABL" field.</summary>
    public const int FHHFPOIAABLFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_fHHFPOIAABL_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> fHHFPOIAABL_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FHHFPOIAABL {
      get { return fHHFPOIAABL_; }
    }

    /// <summary>Field number for the "BLENLMPDLGL" field.</summary>
    public const int BLENLMPDLGLFieldNumber = 7;
    private bool bLENLMPDLGL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BLENLMPDLGL {
      get { return bLENLMPDLGL_; }
      set {
        bLENLMPDLGL_ = value;
      }
    }

    /// <summary>Field number for the "CPBNBJPCNIE" field.</summary>
    public const int CPBNBJPCNIEFieldNumber = 13;
    private bool cPBNBJPCNIE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CPBNBJPCNIE {
      get { return cPBNBJPCNIE_; }
      set {
        cPBNBJPCNIE_ = value;
      }
    }

    /// <summary>Field number for the "NOKHIJCINPH" field.</summary>
    public const int NOKHIJCINPHFieldNumber = 10;
    private uint nOKHIJCINPH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NOKHIJCINPH {
      get { return nOKHIJCINPH_; }
      set {
        nOKHIJCINPH_ = value;
      }
    }

    /// <summary>Field number for the "HCHMOHHKMFP" field.</summary>
    public const int HCHMOHHKMFPFieldNumber = 8;
    private uint hCHMOHHKMFP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HCHMOHHKMFP {
      get { return hCHMOHHKMFP_; }
      set {
        hCHMOHHKMFP_ = value;
      }
    }

    /// <summary>Field number for the "FEFFNCOECHD" field.</summary>
    public const int FEFFNCOECHDFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_fEFFNCOECHD_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> fEFFNCOECHD_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FEFFNCOECHD {
      get { return fEFFNCOECHD_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OHMOEGIOOFJ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OHMOEGIOOFJ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OGADODKGLNL != other.OGADODKGLNL) return false;
      if(!aNGBFBKIFDF_.Equals(other.aNGBFBKIFDF_)) return false;
      if(!fHHFPOIAABL_.Equals(other.fHHFPOIAABL_)) return false;
      if (BLENLMPDLGL != other.BLENLMPDLGL) return false;
      if (CPBNBJPCNIE != other.CPBNBJPCNIE) return false;
      if (NOKHIJCINPH != other.NOKHIJCINPH) return false;
      if (HCHMOHHKMFP != other.HCHMOHHKMFP) return false;
      if(!fEFFNCOECHD_.Equals(other.fEFFNCOECHD_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OGADODKGLNL != 0) hash ^= OGADODKGLNL.GetHashCode();
      hash ^= aNGBFBKIFDF_.GetHashCode();
      hash ^= fHHFPOIAABL_.GetHashCode();
      if (BLENLMPDLGL != false) hash ^= BLENLMPDLGL.GetHashCode();
      if (CPBNBJPCNIE != false) hash ^= CPBNBJPCNIE.GetHashCode();
      if (NOKHIJCINPH != 0) hash ^= NOKHIJCINPH.GetHashCode();
      if (HCHMOHHKMFP != 0) hash ^= HCHMOHHKMFP.GetHashCode();
      hash ^= fEFFNCOECHD_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      fEFFNCOECHD_.WriteTo(output, _repeated_fEFFNCOECHD_codec);
      fHHFPOIAABL_.WriteTo(output, _repeated_fHHFPOIAABL_codec);
      if (OGADODKGLNL != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(OGADODKGLNL);
      }
      if (BLENLMPDLGL != false) {
        output.WriteRawTag(56);
        output.WriteBool(BLENLMPDLGL);
      }
      if (HCHMOHHKMFP != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(HCHMOHHKMFP);
      }
      if (NOKHIJCINPH != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(NOKHIJCINPH);
      }
      aNGBFBKIFDF_.WriteTo(output, _repeated_aNGBFBKIFDF_codec);
      if (CPBNBJPCNIE != false) {
        output.WriteRawTag(104);
        output.WriteBool(CPBNBJPCNIE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      fEFFNCOECHD_.WriteTo(ref output, _repeated_fEFFNCOECHD_codec);
      fHHFPOIAABL_.WriteTo(ref output, _repeated_fHHFPOIAABL_codec);
      if (OGADODKGLNL != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(OGADODKGLNL);
      }
      if (BLENLMPDLGL != false) {
        output.WriteRawTag(56);
        output.WriteBool(BLENLMPDLGL);
      }
      if (HCHMOHHKMFP != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(HCHMOHHKMFP);
      }
      if (NOKHIJCINPH != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(NOKHIJCINPH);
      }
      aNGBFBKIFDF_.WriteTo(ref output, _repeated_aNGBFBKIFDF_codec);
      if (CPBNBJPCNIE != false) {
        output.WriteRawTag(104);
        output.WriteBool(CPBNBJPCNIE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OGADODKGLNL != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OGADODKGLNL);
      }
      size += aNGBFBKIFDF_.CalculateSize(_repeated_aNGBFBKIFDF_codec);
      size += fHHFPOIAABL_.CalculateSize(_repeated_fHHFPOIAABL_codec);
      if (BLENLMPDLGL != false) {
        size += 1 + 1;
      }
      if (CPBNBJPCNIE != false) {
        size += 1 + 1;
      }
      if (NOKHIJCINPH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NOKHIJCINPH);
      }
      if (HCHMOHHKMFP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HCHMOHHKMFP);
      }
      size += fEFFNCOECHD_.CalculateSize(_repeated_fEFFNCOECHD_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OHMOEGIOOFJ other) {
      if (other == null) {
        return;
      }
      if (other.OGADODKGLNL != 0) {
        OGADODKGLNL = other.OGADODKGLNL;
      }
      aNGBFBKIFDF_.Add(other.aNGBFBKIFDF_);
      fHHFPOIAABL_.Add(other.fHHFPOIAABL_);
      if (other.BLENLMPDLGL != false) {
        BLENLMPDLGL = other.BLENLMPDLGL;
      }
      if (other.CPBNBJPCNIE != false) {
        CPBNBJPCNIE = other.CPBNBJPCNIE;
      }
      if (other.NOKHIJCINPH != 0) {
        NOKHIJCINPH = other.NOKHIJCINPH;
      }
      if (other.HCHMOHHKMFP != 0) {
        HCHMOHHKMFP = other.HCHMOHHKMFP;
      }
      fEFFNCOECHD_.Add(other.fEFFNCOECHD_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18:
          case 16: {
            fEFFNCOECHD_.AddEntriesFrom(input, _repeated_fEFFNCOECHD_codec);
            break;
          }
          case 26:
          case 24: {
            fHHFPOIAABL_.AddEntriesFrom(input, _repeated_fHHFPOIAABL_codec);
            break;
          }
          case 40: {
            OGADODKGLNL = input.ReadUInt32();
            break;
          }
          case 56: {
            BLENLMPDLGL = input.ReadBool();
            break;
          }
          case 64: {
            HCHMOHHKMFP = input.ReadUInt32();
            break;
          }
          case 80: {
            NOKHIJCINPH = input.ReadUInt32();
            break;
          }
          case 90:
          case 88: {
            aNGBFBKIFDF_.AddEntriesFrom(input, _repeated_aNGBFBKIFDF_codec);
            break;
          }
          case 104: {
            CPBNBJPCNIE = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18:
          case 16: {
            fEFFNCOECHD_.AddEntriesFrom(ref input, _repeated_fEFFNCOECHD_codec);
            break;
          }
          case 26:
          case 24: {
            fHHFPOIAABL_.AddEntriesFrom(ref input, _repeated_fHHFPOIAABL_codec);
            break;
          }
          case 40: {
            OGADODKGLNL = input.ReadUInt32();
            break;
          }
          case 56: {
            BLENLMPDLGL = input.ReadBool();
            break;
          }
          case 64: {
            HCHMOHHKMFP = input.ReadUInt32();
            break;
          }
          case 80: {
            NOKHIJCINPH = input.ReadUInt32();
            break;
          }
          case 90:
          case 88: {
            aNGBFBKIFDF_.AddEntriesFrom(ref input, _repeated_aNGBFBKIFDF_codec);
            break;
          }
          case 104: {
            CPBNBJPCNIE = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
