// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RogueVirtualItemInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from RogueVirtualItemInfo.proto</summary>
  public static partial class RogueVirtualItemInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for RogueVirtualItemInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RogueVirtualItemInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpSb2d1ZVZpcnR1YWxJdGVtSW5mby5wcm90byJqChRSb2d1ZVZpcnR1YWxJ",
            "dGVtSW5mbxITCgtyb2d1ZV9tb25leRgBIAEoDRITCgtGR0JQSk5ORUVDTRgD",
            "IAEoDRITCgtGSElFS0pDT1BERhgIIAEoDRITCgtJQkRHQ0hOSFBJQRgMIAEo",
            "DUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.RogueVirtualItemInfo), global::EggLink.DanhengServer.Proto.RogueVirtualItemInfo.Parser, new[]{ "RogueMoney", "FGBPJNNEECM", "FHIEKJCOPDF", "IBDGCHNHPIA" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RogueVirtualItemInfo : pb::IMessage<RogueVirtualItemInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RogueVirtualItemInfo> _parser = new pb::MessageParser<RogueVirtualItemInfo>(() => new RogueVirtualItemInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RogueVirtualItemInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.RogueVirtualItemInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueVirtualItemInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueVirtualItemInfo(RogueVirtualItemInfo other) : this() {
      rogueMoney_ = other.rogueMoney_;
      fGBPJNNEECM_ = other.fGBPJNNEECM_;
      fHIEKJCOPDF_ = other.fHIEKJCOPDF_;
      iBDGCHNHPIA_ = other.iBDGCHNHPIA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueVirtualItemInfo Clone() {
      return new RogueVirtualItemInfo(this);
    }

    /// <summary>Field number for the "rogue_money" field.</summary>
    public const int RogueMoneyFieldNumber = 1;
    private uint rogueMoney_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RogueMoney {
      get { return rogueMoney_; }
      set {
        rogueMoney_ = value;
      }
    }

    /// <summary>Field number for the "FGBPJNNEECM" field.</summary>
    public const int FGBPJNNEECMFieldNumber = 3;
    private uint fGBPJNNEECM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FGBPJNNEECM {
      get { return fGBPJNNEECM_; }
      set {
        fGBPJNNEECM_ = value;
      }
    }

    /// <summary>Field number for the "FHIEKJCOPDF" field.</summary>
    public const int FHIEKJCOPDFFieldNumber = 8;
    private uint fHIEKJCOPDF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FHIEKJCOPDF {
      get { return fHIEKJCOPDF_; }
      set {
        fHIEKJCOPDF_ = value;
      }
    }

    /// <summary>Field number for the "IBDGCHNHPIA" field.</summary>
    public const int IBDGCHNHPIAFieldNumber = 12;
    private uint iBDGCHNHPIA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IBDGCHNHPIA {
      get { return iBDGCHNHPIA_; }
      set {
        iBDGCHNHPIA_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RogueVirtualItemInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RogueVirtualItemInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RogueMoney != other.RogueMoney) return false;
      if (FGBPJNNEECM != other.FGBPJNNEECM) return false;
      if (FHIEKJCOPDF != other.FHIEKJCOPDF) return false;
      if (IBDGCHNHPIA != other.IBDGCHNHPIA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RogueMoney != 0) hash ^= RogueMoney.GetHashCode();
      if (FGBPJNNEECM != 0) hash ^= FGBPJNNEECM.GetHashCode();
      if (FHIEKJCOPDF != 0) hash ^= FHIEKJCOPDF.GetHashCode();
      if (IBDGCHNHPIA != 0) hash ^= IBDGCHNHPIA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RogueMoney != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RogueMoney);
      }
      if (FGBPJNNEECM != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(FGBPJNNEECM);
      }
      if (FHIEKJCOPDF != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(FHIEKJCOPDF);
      }
      if (IBDGCHNHPIA != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(IBDGCHNHPIA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RogueMoney != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RogueMoney);
      }
      if (FGBPJNNEECM != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(FGBPJNNEECM);
      }
      if (FHIEKJCOPDF != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(FHIEKJCOPDF);
      }
      if (IBDGCHNHPIA != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(IBDGCHNHPIA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RogueMoney != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RogueMoney);
      }
      if (FGBPJNNEECM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FGBPJNNEECM);
      }
      if (FHIEKJCOPDF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FHIEKJCOPDF);
      }
      if (IBDGCHNHPIA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IBDGCHNHPIA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RogueVirtualItemInfo other) {
      if (other == null) {
        return;
      }
      if (other.RogueMoney != 0) {
        RogueMoney = other.RogueMoney;
      }
      if (other.FGBPJNNEECM != 0) {
        FGBPJNNEECM = other.FGBPJNNEECM;
      }
      if (other.FHIEKJCOPDF != 0) {
        FHIEKJCOPDF = other.FHIEKJCOPDF;
      }
      if (other.IBDGCHNHPIA != 0) {
        IBDGCHNHPIA = other.IBDGCHNHPIA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RogueMoney = input.ReadUInt32();
            break;
          }
          case 24: {
            FGBPJNNEECM = input.ReadUInt32();
            break;
          }
          case 64: {
            FHIEKJCOPDF = input.ReadUInt32();
            break;
          }
          case 96: {
            IBDGCHNHPIA = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RogueMoney = input.ReadUInt32();
            break;
          }
          case 24: {
            FGBPJNNEECM = input.ReadUInt32();
            break;
          }
          case 64: {
            FHIEKJCOPDF = input.ReadUInt32();
            break;
          }
          case 96: {
            IBDGCHNHPIA = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
