// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TelevisionActivityData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from TelevisionActivityData.proto</summary>
  public static partial class TelevisionActivityDataReflection {

    #region Descriptor
    /// <summary>File descriptor for TelevisionActivityData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TelevisionActivityDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxUZWxldmlzaW9uQWN0aXZpdHlEYXRhLnByb3RvIlcKFlRlbGV2aXNpb25B",
            "Y3Rpdml0eURhdGESEwoLSEZLRURMSERLTEUYCCABKA0SEwoLRUdGQkFLS0lQ",
            "T0cYDyABKA0SEwoLTENOTk1MT0hFSEUYBSABKA1CHqoCG0VnZ0xpbmsuRGFu",
            "aGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.TelevisionActivityData), global::EggLink.DanhengServer.Proto.TelevisionActivityData.Parser, new[]{ "HFKEDLHDKLE", "EGFBAKKIPOG", "LCNNMLOHEHE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TelevisionActivityData : pb::IMessage<TelevisionActivityData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TelevisionActivityData> _parser = new pb::MessageParser<TelevisionActivityData>(() => new TelevisionActivityData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TelevisionActivityData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.TelevisionActivityDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TelevisionActivityData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TelevisionActivityData(TelevisionActivityData other) : this() {
      hFKEDLHDKLE_ = other.hFKEDLHDKLE_;
      eGFBAKKIPOG_ = other.eGFBAKKIPOG_;
      lCNNMLOHEHE_ = other.lCNNMLOHEHE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TelevisionActivityData Clone() {
      return new TelevisionActivityData(this);
    }

    /// <summary>Field number for the "HFKEDLHDKLE" field.</summary>
    public const int HFKEDLHDKLEFieldNumber = 8;
    private uint hFKEDLHDKLE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HFKEDLHDKLE {
      get { return hFKEDLHDKLE_; }
      set {
        hFKEDLHDKLE_ = value;
      }
    }

    /// <summary>Field number for the "EGFBAKKIPOG" field.</summary>
    public const int EGFBAKKIPOGFieldNumber = 15;
    private uint eGFBAKKIPOG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EGFBAKKIPOG {
      get { return eGFBAKKIPOG_; }
      set {
        eGFBAKKIPOG_ = value;
      }
    }

    /// <summary>Field number for the "LCNNMLOHEHE" field.</summary>
    public const int LCNNMLOHEHEFieldNumber = 5;
    private uint lCNNMLOHEHE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LCNNMLOHEHE {
      get { return lCNNMLOHEHE_; }
      set {
        lCNNMLOHEHE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TelevisionActivityData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TelevisionActivityData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HFKEDLHDKLE != other.HFKEDLHDKLE) return false;
      if (EGFBAKKIPOG != other.EGFBAKKIPOG) return false;
      if (LCNNMLOHEHE != other.LCNNMLOHEHE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HFKEDLHDKLE != 0) hash ^= HFKEDLHDKLE.GetHashCode();
      if (EGFBAKKIPOG != 0) hash ^= EGFBAKKIPOG.GetHashCode();
      if (LCNNMLOHEHE != 0) hash ^= LCNNMLOHEHE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LCNNMLOHEHE != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(LCNNMLOHEHE);
      }
      if (HFKEDLHDKLE != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(HFKEDLHDKLE);
      }
      if (EGFBAKKIPOG != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(EGFBAKKIPOG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LCNNMLOHEHE != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(LCNNMLOHEHE);
      }
      if (HFKEDLHDKLE != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(HFKEDLHDKLE);
      }
      if (EGFBAKKIPOG != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(EGFBAKKIPOG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HFKEDLHDKLE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HFKEDLHDKLE);
      }
      if (EGFBAKKIPOG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EGFBAKKIPOG);
      }
      if (LCNNMLOHEHE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LCNNMLOHEHE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TelevisionActivityData other) {
      if (other == null) {
        return;
      }
      if (other.HFKEDLHDKLE != 0) {
        HFKEDLHDKLE = other.HFKEDLHDKLE;
      }
      if (other.EGFBAKKIPOG != 0) {
        EGFBAKKIPOG = other.EGFBAKKIPOG;
      }
      if (other.LCNNMLOHEHE != 0) {
        LCNNMLOHEHE = other.LCNNMLOHEHE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 40: {
            LCNNMLOHEHE = input.ReadUInt32();
            break;
          }
          case 64: {
            HFKEDLHDKLE = input.ReadUInt32();
            break;
          }
          case 120: {
            EGFBAKKIPOG = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 40: {
            LCNNMLOHEHE = input.ReadUInt32();
            break;
          }
          case 64: {
            HFKEDLHDKLE = input.ReadUInt32();
            break;
          }
          case 120: {
            EGFBAKKIPOG = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
