// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UpdateRedDotDataCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from UpdateRedDotDataCsReq.proto</summary>
  public static partial class UpdateRedDotDataCsReqReflection {

    #region Descriptor
    /// <summary>File descriptor for UpdateRedDotDataCsReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UpdateRedDotDataCsReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtVcGRhdGVSZWREb3REYXRhQ3NSZXEucHJvdG8aEUNBT0dFSEhETkxJLnBy",
            "b3RvIogBChVVcGRhdGVSZWREb3REYXRhQ3NSZXESEAoIZ3JvdXBfaWQYCCAB",
            "KA0SEwoLc3dpdGNoX2xpc3QYASADKA0SIQoLQ1BPR05ITkFHQUYYCiABKA4y",
            "DC5DQU9HRUhIRE5MSRITCgtMRkFLSEJMSU1MSRgFIAEoDRIQCghwYW5lbF9p",
            "ZBgDIAEoDUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.CAOGEHHDNLIReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.UpdateRedDotDataCsReq), global::EggLink.DanhengServer.Proto.UpdateRedDotDataCsReq.Parser, new[]{ "GroupId", "SwitchList", "CPOGNHNAGAF", "LFAKHBLIMLI", "PanelId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateRedDotDataCsReq : pb::IMessage<UpdateRedDotDataCsReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateRedDotDataCsReq> _parser = new pb::MessageParser<UpdateRedDotDataCsReq>(() => new UpdateRedDotDataCsReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateRedDotDataCsReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.UpdateRedDotDataCsReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateRedDotDataCsReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateRedDotDataCsReq(UpdateRedDotDataCsReq other) : this() {
      groupId_ = other.groupId_;
      switchList_ = other.switchList_.Clone();
      cPOGNHNAGAF_ = other.cPOGNHNAGAF_;
      lFAKHBLIMLI_ = other.lFAKHBLIMLI_;
      panelId_ = other.panelId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateRedDotDataCsReq Clone() {
      return new UpdateRedDotDataCsReq(this);
    }

    /// <summary>Field number for the "group_id" field.</summary>
    public const int GroupIdFieldNumber = 8;
    private uint groupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GroupId {
      get { return groupId_; }
      set {
        groupId_ = value;
      }
    }

    /// <summary>Field number for the "switch_list" field.</summary>
    public const int SwitchListFieldNumber = 1;
    private static readonly pb::FieldCodec<uint> _repeated_switchList_codec
        = pb::FieldCodec.ForUInt32(10);
    private readonly pbc::RepeatedField<uint> switchList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> SwitchList {
      get { return switchList_; }
    }

    /// <summary>Field number for the "CPOGNHNAGAF" field.</summary>
    public const int CPOGNHNAGAFFieldNumber = 10;
    private global::EggLink.DanhengServer.Proto.CAOGEHHDNLI cPOGNHNAGAF_ = global::EggLink.DanhengServer.Proto.CAOGEHHDNLI.UpdateReddotNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.CAOGEHHDNLI CPOGNHNAGAF {
      get { return cPOGNHNAGAF_; }
      set {
        cPOGNHNAGAF_ = value;
      }
    }

    /// <summary>Field number for the "LFAKHBLIMLI" field.</summary>
    public const int LFAKHBLIMLIFieldNumber = 5;
    private uint lFAKHBLIMLI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LFAKHBLIMLI {
      get { return lFAKHBLIMLI_; }
      set {
        lFAKHBLIMLI_ = value;
      }
    }

    /// <summary>Field number for the "panel_id" field.</summary>
    public const int PanelIdFieldNumber = 3;
    private uint panelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PanelId {
      get { return panelId_; }
      set {
        panelId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateRedDotDataCsReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateRedDotDataCsReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GroupId != other.GroupId) return false;
      if(!switchList_.Equals(other.switchList_)) return false;
      if (CPOGNHNAGAF != other.CPOGNHNAGAF) return false;
      if (LFAKHBLIMLI != other.LFAKHBLIMLI) return false;
      if (PanelId != other.PanelId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GroupId != 0) hash ^= GroupId.GetHashCode();
      hash ^= switchList_.GetHashCode();
      if (CPOGNHNAGAF != global::EggLink.DanhengServer.Proto.CAOGEHHDNLI.UpdateReddotNone) hash ^= CPOGNHNAGAF.GetHashCode();
      if (LFAKHBLIMLI != 0) hash ^= LFAKHBLIMLI.GetHashCode();
      if (PanelId != 0) hash ^= PanelId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      switchList_.WriteTo(output, _repeated_switchList_codec);
      if (PanelId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PanelId);
      }
      if (LFAKHBLIMLI != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(LFAKHBLIMLI);
      }
      if (GroupId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GroupId);
      }
      if (CPOGNHNAGAF != global::EggLink.DanhengServer.Proto.CAOGEHHDNLI.UpdateReddotNone) {
        output.WriteRawTag(80);
        output.WriteEnum((int) CPOGNHNAGAF);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      switchList_.WriteTo(ref output, _repeated_switchList_codec);
      if (PanelId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PanelId);
      }
      if (LFAKHBLIMLI != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(LFAKHBLIMLI);
      }
      if (GroupId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GroupId);
      }
      if (CPOGNHNAGAF != global::EggLink.DanhengServer.Proto.CAOGEHHDNLI.UpdateReddotNone) {
        output.WriteRawTag(80);
        output.WriteEnum((int) CPOGNHNAGAF);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GroupId);
      }
      size += switchList_.CalculateSize(_repeated_switchList_codec);
      if (CPOGNHNAGAF != global::EggLink.DanhengServer.Proto.CAOGEHHDNLI.UpdateReddotNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CPOGNHNAGAF);
      }
      if (LFAKHBLIMLI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LFAKHBLIMLI);
      }
      if (PanelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PanelId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateRedDotDataCsReq other) {
      if (other == null) {
        return;
      }
      if (other.GroupId != 0) {
        GroupId = other.GroupId;
      }
      switchList_.Add(other.switchList_);
      if (other.CPOGNHNAGAF != global::EggLink.DanhengServer.Proto.CAOGEHHDNLI.UpdateReddotNone) {
        CPOGNHNAGAF = other.CPOGNHNAGAF;
      }
      if (other.LFAKHBLIMLI != 0) {
        LFAKHBLIMLI = other.LFAKHBLIMLI;
      }
      if (other.PanelId != 0) {
        PanelId = other.PanelId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            switchList_.AddEntriesFrom(input, _repeated_switchList_codec);
            break;
          }
          case 24: {
            PanelId = input.ReadUInt32();
            break;
          }
          case 40: {
            LFAKHBLIMLI = input.ReadUInt32();
            break;
          }
          case 64: {
            GroupId = input.ReadUInt32();
            break;
          }
          case 80: {
            CPOGNHNAGAF = (global::EggLink.DanhengServer.Proto.CAOGEHHDNLI) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            switchList_.AddEntriesFrom(ref input, _repeated_switchList_codec);
            break;
          }
          case 24: {
            PanelId = input.ReadUInt32();
            break;
          }
          case 40: {
            LFAKHBLIMLI = input.ReadUInt32();
            break;
          }
          case 64: {
            GroupId = input.ReadUInt32();
            break;
          }
          case 80: {
            CPOGNHNAGAF = (global::EggLink.DanhengServer.Proto.CAOGEHHDNLI) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
